/**
 * @file string_utils.c
 * @brief Implementation of string manipulation and CSV parsing utilities.
 */

#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "string_utils.h"

/**
 * @brief Duplicates a string.
 * @param s Input string.
 * @return char* Allocated copy of s.
 */
char *StrDup(const char *s) {
    if (!s) return NULL;
    char *d = malloc(strlen(s) + 1);
    if (d) strcpy(d, s);
    return d;
}

/**
 * @brief Trims leading and trailing whitespace from a string in-place.
 * @param s Input string.
 * @return char* Pointer to the trimmed start of the string.
 */
char *StrTrim(char *s) {
    if (!s) return NULL;
    
    // Trim leading whitespace
    while(isspace((unsigned char)*s)) s++;
    
    if(*s == 0) return s; // String consists only of whitespace
    
    // Trim trailing whitespace
    char *end = s + strlen(s) - 1;
    while(end > s && isspace((unsigned char)*end)) end--;
    
    *(end+1) = '\0';
    return s;
}

/**
 * @brief Frees a token array generated by CsvTokenizeLine.
 */
void CsvFreeTokens(char **tokens, int count) {
    if (!tokens) return;
    for (int i = 0; i < count; i++) {
        free(tokens[i]);
    }
    free(tokens);
}

/**
 * @brief A robust CSV line tokenizer.
 * 
 * Correctlly handles:
 * - Quoted fields containing commas.
 * - Escaped double quotes ("").
 * - Newline characters at the end of the line.
 * 
 * @param line The raw CSV line string.
 * @param count Output parameter for the number of tokens found.
 * @return char** Allocated array of token strings.
 */
char **CsvTokenizeLine(const char *line, int *count) {
    if (!line) { *count=0; return NULL; }

    int capacity = 10;
    int nTokens = 0;
    char **tokens = malloc(sizeof(char*) * capacity);
    if(!tokens) return NULL;

    const char *p = line;
    
    while (*p) {
        // Expand token array if needed
        if (nTokens >= capacity) {
            capacity *= 2;
            char **newTokens = realloc(tokens, sizeof(char*) * capacity);
            if (!newTokens) { CsvFreeTokens(tokens, nTokens); *count=0; return NULL; }
            tokens = newTokens;
        }

        // Field parsing logic
        int bufCap = 128; // Larger initial buffer for fields
        int bufLen = 0;
        char *field = malloc(bufCap);
        if (!field) { CsvFreeTokens(tokens, nTokens); *count=0; return NULL; }
        
        int inQuote = 0;
        if (*p == '"') {
            inQuote = 1;
            p++;
        }

        while (*p) {
            // Ensure field buffer has space
            if (bufLen + 1 >= bufCap) {
                bufCap *= 2;
                char *newField = realloc(field, bufCap);
                if (!newField) { free(field); CsvFreeTokens(tokens, nTokens); *count=0; return NULL; }
                field = newField;
            }

            if (inQuote) {
                if (*p == '"') {
                    if (*(p+1) == '"') {
                        field[bufLen++] = '"'; // Escaped quote
                        p += 2;
                    } else {
                        inQuote = 0; // End of quoted section
                        p++;
                    }
                } else {
                    field[bufLen++] = *p++;
                }
            } else {
                if (*p == ',') {
                    p++; // Field delimiter
                    break; 
                } else if (*p == '\r' || *p == '\n') {
                    // Line endings terminate the current field
                    while (*p == '\r' || *p == '\n') p++;
                    break; 
                } else {
                    field[bufLen++] = *p++;
                }
            }
        }
        field[bufLen] = '\0';
        tokens[nTokens++] = field;
    }
    
    *count = nTokens;
    return tokens;
}
